export const AddProductData = [
  {
    sectionName: "Fruits, Vegs & Salads",
    categories: [
      { name: "Fruits" },
      { name: "Vegetables" },
      { name: "Herbs" },
      { name: "Salads" },
    ],
  },
  {
    sectionName: "Home & Kitchen",
    categories: [
      { name: "Bakeware" },
      { name: "Bar accessories" },
      { name: "Bed & Bath" },
      { name: "Room Fragrances" },
      { name: "Cookware" },
      { name: "Drinkware" },
      { name: "Flowers and Vases" },
      { name: "Kitchen store" },
      { name: "Kitchen materials" },
      { name: "Kitchen utensils" },
      { name: "Tableware" },
    ],
  },
  {
    sectionName: "Household & Cleaning",
    categories: [
      { name: "Home Fragrances" },
      { name: "Bleach and Disinfectants" },
      { name: "Cleaning Materials" },
      { name: "Dishwash" },
      { name: "Drain Cleaners" },
      { name: "Dustbins" },
      { name: "Dusters and Swotters" },
      { name: "Floor and Carpet care" },
      { name: "bags, Foils, Paper and Wraps" },
      { name: "Laundry" },
      { name: "Oven Cleaners" },
      { name: "Polishers" },
      { name: "Toilet Papers" },
      { name: "Window Cleaners" },
    ],
  },

  {
    sectionName: "Beverages, Juices and Cordials",
    categories: [
      { name: "Cordials, concenterates and sqashes" },
      { name: "Daily Blends" },
      { name: "Energy Drinks" },
      { name: "Flavored Milk" },
      { name: "Fresh Juice" },
      { name: "Ice Teas and Coffees" },
      { name: "Juices" },
      { name: "Soda Mixers" },
      { name: "Soft Drinks" },
      { name: "Waters" },
    ],
  },
  {
    sectionName: "Bakery",
    categories: [
      { name: "Confectionary" },
      { name: "Bread, Rolls, Wraps and Bagets" },
      { name: "Cakes, Cupcakes and Tarts" },
      { name: "Croissants, Scones and Muffins" },
      { name: "Pies" },
    ],
  },
  {
    sectionName: "Appliances",
    categories: [
      { name: "Beauty Appliances" },
      { name: "Coffee Machines" },
      { name: "Cooking Appliances" },
      { name: "Heating and Cooling" },
      { name: "Irons" },
      { name: "Kettles" },
      { name: "Vacuum Cleaners" },
      { name: "Speciality Appliances" },
      { name: "Soda Machines and Coolers" },
      { name: "Sandwich Makers" },
    ],
  },

  {
    sectionName: "Baby",
    categories: [
      { name: "Antenatal" },
      { name: "Toys" },
      { name: "Clothings and Gifts" },
      { name: "Food and Formula" },
      { name: "Baby Toiletries" },
      { name: "Bath Time" },
      { name: "Car seats" },
      { name: "Nappies and wipes" },
      { name: "Nursery" },
      { name: "Nursing and Feeding" },
      { name: "Prams and Strollers" },
      { name: "Scothers and Teethers" },
    ],
  },
  {
    sectionName: "Beauty",
    categories: [
      { name: "All Fragrances" },
      { name: "Makeup" },
      { name: "Skincare" },
    ],
  },

  {
    sectionName: "Wine, Beers & Spirits ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Beer" },
      { name: "Ciders & Coolers" },
      { name: "Liqueur & Shooters " },
      { name: "Liquor Gifts " },
      { name: "Smokers Accessories" },
      { name: "Spirits " },
      { name: "Wines" },
    ],
  },
  {
    sectionName: "Toys",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Car" },
      { name: "Dolls and Dolls accessories" },
      { name: "For the Playroom " },
      { name: "Games & Puzzles " },
      { name: "Playsets " },
      { name: "Ride Ons" },
      { name: "Soft Toys" },
    ],
  },
  {
    sectionName: "Toiletries",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Bath, Shower & Soap" },
      { name: "Beauty & Skin " },
      { name: "Body Care " },
      { name: "Deodrants " },
      { name: "Facial Care" },
      { name: "Hair Care " },
      { name: "Oral Care" },
      { name: "Sanitary Products " },
      { name: "Sexual Health " },
      { name: "Shavings" },
    ],
  },
  {
    sectionName: "Sweets & Snacks ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Dried Fruits, Nuts & Snacks " },
      { name: "Biscuits, Rusks & Crackers  " },
      { name: "Chewing Gum & Mints  " },
      { name: "Chips, Popcorn & Pretzels " },
      { name: "Chocolates" },
      { name: "Sweets  " },
    ],
  },
  {
    sectionName: "Stationery & Crafts ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Art & Crafts " },
      { name: "Book Covers & Labels" },
      { name: "Books & Notebooks " },
      { name: "Calculators " },
      { name: "Colouring & Painting " },
      { name: "Correction " },
      { name: "Cutting & Sticking " },
      { name: "Filing & Folders " },
      { name: "Hobbies & Crafts" },
      { name: "Newspapers & Magazines " },
      { name: "Office Supplies " },
      { name: "Paper & Card Boards " },
      { name: "Pencil Bags & Cases " },
      { name: "Pens, Pencils & Markers " },
      { name: "Punches & Staplers " },
      { name: "Rulers & Measuring " },
      { name: "Stationery Sets " },
    ],
  },
  {
    sectionName: "Sports ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Bikes & Accessories " },
      { name: " Court & Field Sports " },
      { name: "   Fishing  " },
      { name: "Fitness " },
      { name: " Games & Activities " },
      { name: "Outdoor Games " },
    ],
  },
  {
    sectionName: "Milk, Diary & Eggs ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Butter & Margarine" },
      { name: "Cheese " },
      { name: "Eggs " },
      { name: "Milk & Cream" },
      { name: "Yoghurts" },
    ],
  },
  {
    sectionName: "Meat & Poultry ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Beef" },
      { name: "Sausages" },
      { name: "Burgers & Meatballs " },
      { name: "Fresh Chicken" },
      { name: "Yoghurts" },
      { name: "Festive Favourites" },
      { name: "Lamb" },
      { name: "Livers & Offals" },
      { name: "Mince" },
      { name: "Pork" },
      { name: "Ribs" },
    ],
  },
  {
    sectionName: "Motor Care",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Car Accessories" },
      { name: "Car Care & Cleaning" },
      { name: "Maintainance & Service" },
    ],
  },
  {
    sectionName: "Party Shop & Occasions",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Balloons" },
      { name: "Décor & Accessories" },
      { name: "Festive" },
      { name: "Gift Wrapping, Boxes & Bags" },
      { name: "Greeting Cards" },
      { name: "Invitations" },
      { name: "   Novelty Toys & Gifts " },
      { name: "Invitations" },
      { name: "Novelty Toys & Gifts" },
      { name: "Party Candles" },
      { name: "Party Tableware" },
    ],
  },
  {
    sectionName: "Party Shop & Occasions",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Balloons" },
      { name: "Décor & Accessories" },
      { name: "Festive" },
      { name: "Gift Wrapping, Boxes & Bags" },
      { name: "Greeting Cards" },
      { name: "Invitations" },
      { name: "   Novelty Toys & Gifts " },
      { name: "Invitations" },
      { name: "Novelty Toys & Gifts" },
      { name: "Party Candles" },
      { name: "Party Tableware" },
    ],
  },
  {
    sectionName: "Pets",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Cat Food & Accessories" },
      { name: "Cat Litter & Trays" },
      { name: "Dog Food & Accessories " },
      { name: "Health & Wellness" },
      { name: "Hygiene &  Grooming" },
      { name: "Pet Beds & Pet Baskets" },
      { name: "Small Pets " },
    ],
  },
  {
    sectionName: "Food Cupboard ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Breakfast Cereals, Porridge & Pap" },
      { name: "Cans, Tins & Jars" },
      { name: "Condiments, Sauces & Marinades" },
      { name: "Cook-In Sauces & Kits" },
      { name: "Crackers & Crispbreads" },
      { name: "Custard, Jellies & Puddings" },
      { name: "Flour & Baking" },
      { name: "   Health Foods & Drinks" },
      { name: "   Herbs, Spices & Seasoning " },
      { name: "   Jams, Honey & Spreads " },
      { name: "   Long Life Milk & Dairy Alternatives" },
      { name: "   Meal Kits" },
      { name: "Oils, Salad Dressing & Vinegars" },
      { name: "   Packed Soup, Stocks & Gravy" },
      { name: "   Pasta, Rice, Grains & Legumes " },
      { name: "   Sugar & Sweeteners" },
    ],
  },
  {
    sectionName: "   Food Cupboard ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Breakfast Cereals, Porridge & Pap" },
      { name: "Cans, Tins & Jars " },
      { name: "Condiments, Sauces & Marinades " },
      { name: "Cook-In Sauces & Kits" },
      { name: "Crackers & Crispbreads" },
      { name: "Custard, Jellies & Puddings" },
      { name: "Flour & Baking" },
      { name: "Health Foods & Drinks" },
      { name: "   Herbs, Spices & Seasoning " },
      { name: "   Jams, Honey & Spreads" },
      { name: "   Long Life Milk & Dairy Alternatives" },
      { name: "   Meal Kits" },
      { name: "Oils, Salad Dressing & Vinegars" },
      { name: "   Packed Soup, Stocks & Gravy" },
      { name: "   Pasta, Rice, Grains & Legumes " },
      { name: "      Sugar & Sweeteners " },
    ],
  },
  {
    sectionName: "Luggage & Bags",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "   Backpacks " },
      { name: "   Bags & Vanity cases" },
      { name: "   Laptop Bags " },
      { name: "   Luggage Accessories" },
      { name: "   Luggage Cases" },
      { name: "  Shopping Bags " },
    ],
  },
  {
    sectionName: "Frozen Food ",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Frozen Burgers " },
      { name: "   Frozen Chips & Potatoes " },
      { name: "        Frozen Desserts & Ice Cream" },
      { name: "         Frozen Fruit & Ice" },
      { name: "      Frozen Health Foods" },
      { name: "     Frozen Meat & Poultry " },
      { name: " Frozen Pizza, Pies & Pastries " },
      { name: "    Frozen Vegetables  " },
      { name: "          Frozen Ready Meals    " },
    ],
  },
  {
    sectionName: "Healthcare",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "At Home Tests" },
      { name: "   Baby Medicine " },
      { name: "Colds & Flu" },
      { name: "   Digestive Health " },
      { name: "Eye & Ear" },
      { name: "First Aid " },
      { name: "   Hosiery & Haberdashery" },
      { name: "   Kids Vitamins  " },
      { name: "   Pain Medicines" },
      { name: "  Sexual Health" },
      { name: "Sports Nutrition & Slimming" },
      { name: "Sun Care" },
      { name: "   Traditional Remedies" },
      { name: "   Vitamins & Supplements " },
    ],
  },
  {
    sectionName: "Fish & Seafood",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "   Crumbed Fish" },
      { name: "      Fish" },
      { name: "      Sea Food" },
    ],
  },
  {
    sectionName: "Garden & Pool",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "   Garden" },
      { name: "      Garden Power Tools" },
      { name: "         Pool & Pool Care" },
    ],
  },
  {
    sectionName: "   E-Cigarettes",
    // sectionImage: Beauty?.HeaderImage,
    categories: [{ name: "   E-Cigarettes" }],
  },
  {
    sectionName: "Ready Meals & Desserts",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "Desserts & Puddings" },
      { name: "   Entertaining " },
      { name: " Food To Go" },
      { name: "      Fresh Sauce & Pastes" },
      { name: "   Heat & Eat Meals" },
      { name: "        Pies & Quiches " },
      { name: "Pizzas & Pizzas Bases" },
      { name: "     Ready To Cook" },
      { name: "    Salads " },
      { name: "  Soups " },
      { name: "Subs, Sandwiches & Wraps " },
    ],
  },
  {
    sectionName: "Electronics",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "   Cameras & Drones" },
      { name: "Cellphone Accessories " },
      { name: "Computers & Accessories" },
      { name: "Energy Solutions" },
      { name: "Gadgets" },
      { name: "Gaming  " },
      { name: " Handsets & Tablets" },
      { name: "   Headphones & Earphones " },
      { name: "   Speakers & Sound" },
      { name: "Tv & Tv Accessories" },
      { name: "   Wearables " },
    ],
  },
  {
    sectionName: "Electronics",
    // sectionImage: Beauty?.HeaderImage,
    categories: [
      { name: "   Cameras & Drones" },
      { name: "Cellphone Accessories " },
      { name: "Computers & Accessories" },
      { name: "Energy Solutions" },
      { name: "Gadgets" },
      { name: "Gaming  " },
      { name: " Handsets & Tablets" },
      { name: "   Headphones & Earphones " },
      { name: "   Speakers & Sound" },
      { name: "Tv & Tv Accessories" },
      { name: "   Wearables " },
    ],
  },
  // {
  //   sectionName: "Camping ",
  //   categories: [
  //     { name: "All Fragrances" , images:CampingAndOutdoor?.},
  //     { name: "Makeup" },
  //     { name: "Skincare" },
  //   ],
  // },
];
