// import { Geist, Geist_Mono } from "next/font/google";
import { Raleway } from "next/font/google";
import Chakrawrap from "./component/app_wraps/Chakrawrap";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-raleway', // optional: use this if you want to apply with CSS variables
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={raleway.className}
      >
        <Chakrawrap>
        {children}
        </Chakrawrap>
      </body>
    </html>
  );
}
